MINI ss13 content and 14 reverts
Cybersun-Industries/ServerBuild pull request #117
Opened 2024-04-08 18:39 UTC by Ilysha998

## Описание PR

Добавляет большие движки для мапперов/ивентеров. Добавляет такси и грузоботов (убрана зависимость от Vehicle)
**Медиа**

**Проверки**

- [x] PR полностью завершён и мне не нужна помощь чтобы его закончить.
- [x] Я внимательно просмотрел все свои изменения и багов в них не нашёл.
- [x] Я запускал локальный сервер со своими изменениями и всё протестировал.
- [x] Я добавил скриншот/видео демонстрации PR в игре, **или** этот PR этого не требует.

**Изменения**

:cl:
- add: Добавлены двигатели и боты

2024-04-10 03:42 UTC, Ilysha998 commented
> _some checks attacks you_

2024-04-11 11:37 UTC, Ilysha998 commented
уээ

2024-04-12 04:14 UTC, Ilysha998 commented
я разобрался вроде, щиткод транспорт заменю на человеческий

2024-04-15 04:57 UTC, gitdubses requested changes
Убери весь транспорт до его переработки. Замени "Хонк киборг" на маленькую букву в локализации. Сделай слот для рюкзака с Хонкертоном под хонк киборга. Сделай локализацию для Mobile Blaster Unit. Сделай локализацию для artifact construct. Зачем нужны эти мобы?

2024-04-15 06:23 UTC, Ilysha998 commented
> Убери весь транспорт до его переработки. Замени "Хонк киборг" на маленькую букву в локализации. Сделай слот для рюкзака с Хонкертоном под хонк киборга. Сделай локализацию для Mobile Blaster Unit. Сделай локализацию для artifact construct. Зачем нужны эти мобы?

Юниты для обомков, конструкт для реакции артефакта. Времени пока нету доделать их. Пока что могут быть использоввнны для ивентов.

2024-04-16 12:35 UTC, gitdubses commented
> > Убери весь транспорт до его переработки. Замени "Хонк киборг" на маленькую букву в локализации. Сделай слот для рюкзака с Хонкертоном под хонк киборга. Сделай локализацию для Mobile Blaster Unit. Сделай локализацию для artifact construct. Зачем нужны эти мобы?
> 
> Юниты для обомков, конструкт для реакции артефакта. Времени пока нету доделать их. Пока что могут быть использоввнны для ивентов.

Так доделывай либо удаляй

2024-04-19 15:07 UTC, gitdubses commented on Resources/Prototypes/Entities/Objects/Specific/Robotics/borg_modules.yml
Нет, имелось в виду в плане того, что у самого борга будет рюкзак хонкертона, то есть слот под него. А добавлять в клоунский модуль рюкзак, как по мне жёсткие костыли.

2024-04-21 10:54 UTC, freeze2222 approved these changes

2024-04-21 11:14 UTC, closed without merging