Posters
Cybersun-Industries/ServerBuild pull request #54
Opened 2024-02-27 13:37 UTC by Ilysha998

## Описание PR

Добавление 14 новых декоративных постеров
**Медиа**

![image](https://github.com/Cybersun-Industries/ServerBuild/assets/86671841/1d0a500d-e01f-4c63-a041-675c0f8e25cc)

**Проверки**

- [x] PR полностью завершён и мне не нужна помощь чтобы его закончить.
- [x] Я внимательно просмотрел все свои изменения и багов в них не нашёл.
- [x] Я запускал локальный сервер со своими изменениями и всё протестировал.
- [x] Я добавил скриншот/видео демонстрации PR в игре, **или** этот PR этого не требует.

**Изменения**

:cl:
- add: Добавлено 14 постеров

2024-02-27 13:53 UTC, KTDR-null commented
А локализация?

2024-02-28 18:20 UTC, freeze2222 submitted a review, later dismissed

2024-02-28 19:43 UTC, gitdubses requested changes
Закинь свои спрайты в Structures/Wallmounts/posters.rsi папку, а потом мету напиши для них.

2024-02-28 19:43 UTC, gitdubses commented on Resources/Prototypes/Entities/Markers/Spawners/Random/posters.yml
У него путь Structures/Wallmounts/posters.rsi, а твои постеры в Radium/Wallmounts/posters.rsi, он просто спавнить не будет плакаты так как найти их не может. А ещё путь должен быть Radium/Structures/Wallmounts/posters.rsi

2024-03-01 19:34 UTC, freeze2222 requested changes

2024-03-01 19:34 UTC, freeze2222 commented on Resources/Textures/Structures/Wallmounts/posters.rsi/meta.json
Вынеси все кастомные постеры в rsi в папке Радиума, в прототипе укажи путь до rsi Радиума, вместо общего.

2024-03-01 19:47 UTC, gitdubses commented on Resources/Textures/Structures/Wallmounts/posters.rsi/meta.json
Так спавнить постеры он только его будет, а ещё выдавать ошибку будет что основных плакатов нет. Делать отдельный спавнер бессмысленно, вот и остаётся один вариант.

2024-03-02 18:18 UTC, merged